<?php
namespace app\home\controller;

use think\Controller;
use think\Db;

class Base extends Controller
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $is_close = Db::name('options')->where('option_id', 6)->value('is_close');
        if (empty($is_close)) {
            echo edd_error('系统维护中...');
            die;
        }
    }
}