<?php
namespace app\home\controller;
use think\Db;

/**
 * 商品、充值
 */
class Goods extends Base
{
    static $cid;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (input('?cid')) {
            self::$cid = open_secret(input('cid'));
        }
    }
    //商品页面
    function home_page()
    {
        $account= account(self::$cid);//商品折扣
        $goodsArr = goods_list();
        foreach ($goodsArr as $k=>$v){
            $goodsArr[$k]['add_diamond'] = floor($v['diamond'] * $account);
        }
        echo edd_success($goodsArr);
    }

    //充值列表
    function recharge_list()
    {
        $pay_log=Db::name('pay_log')
            ->where('player_id', self::$cid)
            ->order('pay_date desc')
            ->field('order_sn,pay_money,diamond_nums,pay_date,player_id')
            ->page(input('page'),6)
            ->select();

        foreach ($pay_log as $k=>$v){
            if (get_player($v['player_id'], 'users_id') == 0) {
                $pay_log[$k]['qcoder']='暂无';
            }else{
                $pay_log[$k]['qcoder']=createCode(get_player($v['player_id'], 'users_id'));
            }
        }
        echo edd_success($pay_log);
    }
    //充值逻辑
    function recharge_think()
    {
        $goods_id = input('goods_id');
        $account = account(self::$cid);//应付的折扣
        $money=get_goods($goods_id, 'money');
        $pay_money = $money;
        $diamond_nums = get_goods($goods_id, 'diamond');//砖石个数
        $map = [
            'order_sn' => sp_get_order_sn(),
            'pay_date' => time(),
            'player_id' => self::$cid,
            'pay_money' => $pay_money,
            'diamond_nums'=>$diamond_nums+floor($account*$diamond_nums),
            'account'=>$account,
            'money'=>$money
        ];

        $pay_log=Db::name('pay_log')
            ->where('order_sn', $map['order_sn'])
            ->select();

        if (empty($pay_log)) {
            if ($pay_id=Db::name('pay_log')->insertGetId($map)) {
                profile_percent(self::$cid,$money,$pay_id);

                save_player_diamond(self::$cid, $diamond_nums, 'inc');

                echo edd_success('充值成功');
            }else{
                 echo edd_error('充值失败');
            }
        }

    }
}