<?php
namespace app\home\controller;
use GatewayClient\Gateway;
use think\cache\driver\Memcache;
use think\Controller;
use think\Db;
/**
 * 新闻通告
 */
class Home extends Controller
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        vendor('gateway.gatewayclient.Gateway');
    }

    function get_time(){
    	echo date("Y-m-d H:i:s",time());
    }
    //首页
    function home_page()
    {
        //最新资讯
        $news['news'] = get_news('首页最新资讯');
        //首页滚动消息
        $news['newsRoll'] = get_news('首页新闻滚动条');
        echo edd_success($news);
    }

    //桌布和卡片壁纸
    function table_card_pic()
    {
        $mem = new Memcache();
        if (!$mem->has('card_pic')) {
            $mem->set('card_pic', get_game_pic('card_pic'));
        }
        $map = [
            'card_pic'=>$mem->get('card_pic'),
        ];

        echo edd_success($map);
    }

    //联系我们
    function connect()
    {
        $map['tel'] = get_options('tel');
        $map['qq'] = get_options('hezuoQQ');
        $map['weixin_public'] = get_options('weixingongzong');
        $map['kefu_qq'] = get_options('kefuQQ');

        echo edd_success($map);
    }

    //语音存储
    function save_radio()
    {
        $room_id = input('room_id');
        $cid = input('cid');
        $inner = "inner".$room_id;

        $file=request()->file('radio');
        $info = $file->rule('uniqid')->move(ROOT_PATH . 'data' . DS . 'upload/'.'home/radio');

        if ($info) {
            $drivePath= $info->getSaveName();
        }else{
            $drivePath = '';
        }
        $Url = 'home/radio/';//上传缩略图
        $thumbUrl = config('view_replace_str.__UPLOAD__') .'/'.$Url .strtr($drivePath, "\\", "/") ;
        $map = [
            'cid'=>open_secret($cid),
            'voice_url' => $thumbUrl,
        ];
        Gateway::sendToGroup($inner, send_client($map, 'play_voice'));
        $watch_dog = 'watch_dog' . $room_id;
        Gateway::sendToGroup($watch_dog, send_client($map, 'play_voice'));
    }

    //战绩回放
    function joined_room()
    {
        $cid = open_secret(input('cid'));
        $likeVar = '\"'.$cid.'\"';
        $map = [
            'all_player' => ['like', '%' . $likeVar . '%'],
        ];
        $room_round=Db::name('room_round')
            ->alias('rr')
            ->where($map)
            ->order('room_date desc')
            ->join('room r','r.room_id=rr.room_id')
            ->page(input('page'),6)
            ->field('r.room_id,room_date,round_times,room_type,room_code,room_all_type')
            ->group('r.room_id')
            ->select();

        foreach ($room_round as $k=>$v){
            $room_round[$k]['all_score'] = $this->all_score($v['room_id'], $cid);
        }
        echo edd_success($room_round);
    }

    //某一局
    function one_room_round()
    {
        $cid = open_secret(input('cid'));
        $room_id = input('room_id');
        $map = [
            'r.player_id'=>$cid,
            'r.room_id' => $room_id,
        ];
        $one_room_round = Db::name('round')
            ->alias('r')
            ->join('bomb b','r.round_id=b.room_id','left')
            ->where($map)
            ->field('score,r.round_id')
            ->select();

        foreach ($one_room_round as $k=>$v){
            $bomb_info = $this->bomb_round($v['round_id'], $room_id);
            $one_room_round[$k]['bomb_nums'] = $bomb_info['bomb_nums'];
            $one_room_round[$k]['bei_lu'] = $bomb_info['bei_lu'];
        }
        echo edd_success($one_room_round);
    }
    //总的分数
    function all_score($room_id,$cid)
    {
        $map = [
            'player_id'=>$cid,
            'room_id'=>$room_id
        ];
        return Db::name('round')
            ->where($map)
            ->sum('score');
    }

    //每局的炸弹倍率
    function bomb_round($round_id, $room_id)
    {
        $room_info = get_home_info($room_id);
        $map = [
            'bei_lu' => 1,
            'bomb_nums' => 0,
        ];
        if ($room_info['double']) {
            $map = [
                'round_id'=>$round_id,
                'room_id'=>$room_id
            ];
            $bomb_nums= Db::name('bomb')->where($map)->count();
            $map['bei_lu'] = pow(2,$bomb_nums);
            $map['bomb_nums'] = $bomb_nums;
        }

        return $map;
    }
}