<?php
namespace app\home\controller;
use GatewayClient\Gateway;
use think\cache\driver\Memcache;
use think\Db;

/**
 * 用户信息
 */
class Player extends Base
{
    static $cid;
    static $mem;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (input('?cid')) {
            self::$cid = open_secret(input('cid'));
        }
    }

    //用户信息
    function get_player_info()
    {
        if (input('?cid')) {
            $player = Db::name('player')->find(self::$cid);
            if (empty($player)) {
                echo edd_error('该用户不存在');
                die;
            }
        }else{
            $openid = input('openid');
            $is_cunzai=Db::name('player')
                ->where('openid', $openid)
                ->find();

            if (empty($is_cunzai)) {
                $addSave = $_POST;
                $addSave['create_time'] = time();
                $new_player_id=Db::name('player')->insertGetId($addSave);
                $player = Db::name('player')->find($new_player_id);
            } else {
                $player = Db::name('player')->where('openid', input('openid'))->find();

            }
        }
        $player_id = $player['player_id'];
        self::$mem = new Memcache();
        self::$mem->set($player_id, $player);

        $player['player_id']=str_pad($player_id,8,'0',STR_PAD_LEFT);
        $player['token'] = set_secret($player_id);

        echo edd_success($player);
    }

    //输入邀请码页面
    function invite_page()
    {
        $users_id=get_player(self::$cid, 'users_id');
        if (!empty($users_id)) {
            echo edd_success(createCode($users_id));
        }else{
            echo edd_success('');
        }
    }

    //邀请码逻辑
    function invite_think()
    {
        $users_id = get_player(self::$cid, 'users_id');
        $code = decode(strtoupper(input('code')));//邀请码解码

        $user=Db::name('users')
            ->where('player_id', self::$cid)
            ->select();

        if (!empty($user)) {
            echo edd_error('代理无法使用该邀请码');
            die;
        }

        if (!empty($users_id)) {
            echo edd_error('已经绑定代理,无法修改');
        } else {
            $agency_id=get_agency($code, 'name');
            if (empty($agency_id)) {
                echo edd_error('您输入的邀请码有误,该代理不存在');
            }else{
                $saveMap = [
                    'player_id'=>self::$cid,
                    'users_id'=>$code
                ];
                if (Db::name('player')->update($saveMap)) {
                    save_child($code,'inc');
                    echo edd_success('邀请码绑定成功');
                }else{
                    echo edd_error('邀请码绑定失败');
                }
            }
        }
    }
}