<?php
namespace app\admin\controller;
use GatewayClient\Gateway;
use think\cache\driver\Memcache;
use think\Db;

/**
 * 数据统计
 */
class Alldata extends Base
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        vendor('gateway.gatewayclient.Gateway');
    }

    //统计块
    function show_page()
    {
        $map['all_player'] = self::all_player();
        $map['today_room_nums'] = self::today_room_nums()?self::today_room_nums():0;
        $map['now_week_pay'] = self::now_week_pay()?self::now_week_pay():0;
        $map['now_week_draw'] = self::now_week_draw()?self::now_week_draw():0;
        $map['now_week_profile'] = self::all_profile()?self::all_profile():0;
        return view('all_data_page',$map);
    }

    //曲线图
    function data_chat()
    {
        $map['per_week_room_nums']=self::per_week_room_nums();
        $map['per_month_pay']=self::per_month_pay();
        $map['per_month_draw']=self::per_month_draw();
        echo json_encode($map);
    }

    static function all_player()
    {
        return Db::name('player')->count();
    }

    //当天的房间总数
    static function today_room_nums()
    {
        $today = strtotime(date('Y-m-d'));
        $tonight = strtotime(date('Y-m-d'))+ 86400;

        $today_room_nums = Db::name('room')
            ->where('room_date',['>',$today],['<',$tonight],'and')
            ->count();

        return $today_room_nums;
    }

    //本周的充值金额
    static function now_week_pay()
    {
        $start = strtotime(date("Y-m-d H:i:s", mktime(0, 0, 0, date("m"), date("d") - date("w") + 1, date("Y"))));
        $end = strtotime(date("Y-m-d H:i:s", mktime(23, 59, 59, date("m"), date("d") - date("w") + 7, date("Y"))));

        $now_week_pay = Db::name('pay_log')
            ->where('pay_date',['>',$start],['<',$end],'and')
            ->sum('pay_money');

        return $now_week_pay;
    }

    //本周提现金额
    static function now_week_draw()
    {
        $start = strtotime(date("Y-m-d H:i:s", mktime(0, 0, 0, date("m"), date("d") - date("w") + 1, date("Y"))));
        $end = strtotime(date("Y-m-d H:i:s", mktime(23, 59, 59, date("m"), date("d") - date("w") + 7, date("Y"))));

        $now_week_draw = Db::name('draw')
            ->where('draw_date',['>',$start],['<',$end],'and')
            ->sum('draw_money');

        return $now_week_draw;
    }

    //平台总盈利
    static function all_profile()
    {
        $now_week_pay = Db::name('pay_log')
            ->sum('pay_money');

        $now_week_draw = Db::name('draw')
            ->sum('draw_money');

        return $now_week_pay - $now_week_draw;
    }
    //每周房间数统计
   static function per_week_room_nums()
    {
        $orderAll=Db::query("SELECT FROM_UNIXTIME(room_date,'%Y-%u') week,COUNT(room_id) room_nums  FROM edd_room GROUP BY week");
        $order['week'] = array_column($orderAll, 'week');
        $order['room_nums'] = array_column($orderAll, 'room_nums');
        return $orderAll;
    }

    //充值记录
    static function per_month_pay()
    {
        $chongzhi=Db::query("SELECT FROM_UNIXTIME(pay_date,'%Y-%m') month,sum(pay_money) pay_money  FROM edd_pay_log GROUP BY month");
        $chong['month'] = array_column($chongzhi, 'month');
        $chong['pay_money'] = array_column($chongzhi, 'pay_money');
        return $chongzhi;
    }

    //提现记录
    static function per_month_draw()
    {
        $draw=Db::query("SELECT FROM_UNIXTIME(draw_date,'%Y-%m') month,sum(draw_money) draw_money  FROM edd_draw GROUP BY month");
        $drawnew['month'] = array_column($draw, 'month');
        $drawnew['draw_money'] = array_column($draw, 'draw_money');
        return $draw;
    }

    //连接websocket,绑定
    function connect()
    {
        $onlineNums = 'onlineNums';

        Gateway::bindUid(input('client_id'), input('name'));
        echo json_encode(Gateway::getClientCountByGroup($onlineNums));
    }
}