<?php
namespace app\admin\controller;

use app\common\controller\Common;

/**
 * 基础控制器
 */
class Base extends Common
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!$this->is_login()) {
            $this->redirect('admin/Login/show_login');
        }

        $auth = new \Auth();
        if ($auth->check(open_secret(cookie('UID')))!='ok') {
            $this->error($auth->getError());
        }
    }

}